[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "term-timer"
dynamic = ["version"]
description = "Speed Cubing Timer on your Terminal"
readme = "README.md"
requires-python = ">=3.12"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["rubick", "cube", "speedcubing", "solve", "timer"]
authors = [{name = "Fantomas42", email = "fantomas42@gmail.com"}]
classifiers = [
  "Programming Language :: Python"
]
dependencies = [
    "plotext==5.3.2",
    "rich>=14.2.0",
    "textual==6.6.0",
    "bleak==1.1.0",
    "Jinja2==3.1.6",
    "bottle==0.13.3",
    "cryptography==49.0.0",
    "kociemba==1.2.1",
    "cubing_algs==1.0.20",
    "rtoml>=0.12.0",
    "numpy>=2.4.0",
    "sounddevice>=0.5.3",
    "fsrs>=6.3.1",
    "wakepy>=0.10.2"
]

[project.urls]
repository = "https://github.com/Fantomas42/term-timer"

[project.optional-dependencies]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-subtests",
]
opengl = [
    "pyopengl",
    "pygame",
]

[project.scripts]
bt-info = "term_timer.scripts.bluetooth_info:main"
term-timer = "term_timer.scripts.timer:main"

[tool.setuptools]
packages = ["term_timer"]

[tool.setuptools.dynamic]
version = {attr = "term_timer.__version__"}

[tool.setuptools.package-data]
term_timer = ["methods/masks/*.json"]

[tool.ruff]
line-length = 80
indent-width = 4
target-version = "py312"
show-fixes = true

[tool.ruff.lint]
preview = true
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    "PT009",
    "PT027",
    "CPY001",
    "D203",
    "D205",
    "D212",
    "RUF067",
    "TD003",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
"term_timer.colors.Color" = "C"

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint.pylint]
allow-magic-value-types = ["str", "int"]

[tool.mypy]
disable_error_code = ["import-untyped"]
exclude = ["poc"]
python_version = 3.12

[tool.pyright]
include = ["term_timer"]
exclude = [
  "term_timer/tests",
  "term_timer/poc",
]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportMissingImports = true

[tool.coverage.run]
branch = true
omit = [
  "term_timer/tests/*",
  "term_timer/poc/*",
  "term_timer/scripts/*",
  "term_timer/opengl/*",
]

[tool.coverage.report]
show_missing = true
