name: Release
permissions:
  contents: read

on:
  push:
    tags: ["v*"]


jobs:
  Release:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/term-timer
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Running the tests
      run: |
        pytest term_timer
    - name: Build packages
      run: |
        python -m pip install build cibuildwheel
        python -m build --sdist
        python -m cibuildwheel --output-dir dist
    - name: Publish release to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
